Repository markdino/Construction-website-1, pull requests merged in 2019-08, with the labels that each got.

#5 Feat: Project component
  src/components/about.js
  src/components/about.scss
  src/components/layout.scss
  src/components/projCard.js
  src/components/project.js
  src/components/project.scss
  src/components/quote.scss
  src/images/polygon.png
  src/images/projects/etienne-beauregard-riverin-B0aCvAVSX8E-unsplash.jpg
  src/images/projects/ialicante-mediterranean-homes-2d4lAQAlbDA-unsplash.jpg
  src/images/projects/jarek-ceborski-jn7uVeCdf6U-unsplash.jpg
  src/images/projects/jason-briscoe-AQl-J19ocWE-unsplash.jpg
  src/images/projects/lance-anderson-QdAAasrZhdk-unsplash.jpg
  src/images/projects/pixasquare-4ojhpgKpS68-unsplash.jpg
  src/pages/index.js
  src/themes/bootstrap-color.scss
  src/themes/green.scss
  src/themes/orange.scss
Labels: enhancement

#6 feat: Add News component for Company News
  src/assets/svg/clock.svg
  src/assets/svg/link.svg
  src/components/layout.scss
  src/components/news.js
  src/components/newsCard.js
  src/components/newsCard.scss
  src/components/project.scss
  src/components/quote.scss
  src/images/news/building.jpg
  src/images/news/seminar.jpg
  src/images/news/team-building.jpg
  src/pages/index.js
  src/themes/green.scss
  src/themes/orange.scss
Labels: enhancement

#7 Feat: Footer component
  gatsby-config.js
  src/assets/svg/calendar.svg
  src/assets/svg/facebook.svg
  src/assets/svg/instagram.svg
  src/assets/svg/linkedin.svg
  src/assets/svg/mail.svg
  src/assets/svg/map-pin.svg
  src/assets/svg/smartphone.svg
  src/assets/svg/twitter.svg
  src/components/footer.js
  src/components/footer.scss
  src/components/header.js
  src/components/layout.js
  src/components/layout.scss
  src/images/badge/ISO-14001.png
  src/images/badge/ISO-45001.png
  src/images/badge/ISO-9001.png
  src/images/badge/pca.png
  src/images/badge/pcab.png
  src/images/philippines.jpg
  src/themes/green.scss
  src/themes/orange.scss
Labels: enhancement

#8 Fix: content overflow and existing padding of ul element
  src/components/footer.scss
  src/components/newsCard.scss
Labels: fix

#9 Feat: Services page
  gatsby-config.js
  src/assets/svg/phone.svg
  src/components/footer.js
  src/components/footer.scss
  src/components/header.js
  src/components/hero.js
  src/components/layout.js
  src/components/layout.scss
  src/components/pageHeader.js
  src/components/pageHeader.scss
  src/components/service.scss
  src/components/services.scss
  src/pages/services.js
  src/themes/green.scss
  src/themes/orange.scss
Labels: enhancement

#12 Feat: Contact page
  gatsby-config.js
  src/components/header.js
  src/components/layout.scss
  src/components/quote.js
  src/pages/contact.js
  src/pages/contact.scss
  src/themes/green.scss
  src/themes/orange.scss
Labels: enhancement, fix
